# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-05 06:26
from __future__ import unicode_literals

from django.db import migrations

from ..models import PREDEFINED_TOASTR_TYPES


def preinstall_toastr(apps, schema_editor):
    ToastrType = apps.get_model('toastr', 'ToastrType')
    db_alias = schema_editor.connection.alias
    for title, color in PREDEFINED_TOASTR_TYPES.items():
        toastr = ToastrType.objects.create(
            title=title,
            color=color
        )
        toastr.save()



class Migration(migrations.Migration):

    dependencies = [
        ('toastr', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            migrations.RunPython.noop,
            preinstall_toastr,
        ),
    ]
